namespace EEGMonitor.Models;

public enum ClinicalEventType
{
    Induction,
    Intubation,
    Incision,
    DrugAdministration,
    Extubation,
    Emergence,
    Custom,
    AutoAlert_LowBIS,
    AutoAlert_HighBIS,
    AutoAlert_LowSpO2,
}

public class ClinicalEvent
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public DateTime Timestamp { get; set; } = DateTime.Now;
    public ClinicalEventType EventType { get; set; }
    public string Label { get; set; } = string.Empty;
    public string Notes { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }

    // Snapshot of vitals at event time
    public double? BISAtEvent { get; set; }
    public double? SpO2AtEvent { get; set; }
    public double? HRAtEvent { get; set; }
    public double? SQIAtEvent { get; set; }

    // Offset from session start (for playback timeline)
    public TimeSpan SessionOffset { get; set; }

    public override string ToString() => $"[{Timestamp:HH:mm:ss}] {EventType}: {Label}";
}
