using EEGMonitor.Models;
using Microsoft.Extensions.Logging;

namespace EEGMonitor.Services.Events;

public interface IEventAnnotationService
{
    IReadOnlyList<ClinicalEvent> Events { get; }
    event Action<ClinicalEvent>? EventAdded;

    ClinicalEvent AddEvent(ClinicalEventType type, string label, string notes = "",
        double? bis = null, double? spo2 = null, double? hr = null, double? sqi = null,
        DateTime? sessionStart = null);
    void AutoCheckThresholds(double bis, double spo2, double sqi, DateTime sessionStart);
}

public sealed class EventAnnotationService : IEventAnnotationService
{
    private readonly ILogger<EventAnnotationService> _logger;
    private readonly List<ClinicalEvent> _events = new();

    private bool _lowBISAlerted;
    private bool _highBISAlerted;
    private bool _lowSpO2Alerted;

    public IReadOnlyList<ClinicalEvent> Events => _events;
    public event Action<ClinicalEvent>? EventAdded;

    public EventAnnotationService(ILogger<EventAnnotationService> logger)
    {
        _logger = logger;
    }

    public ClinicalEvent AddEvent(ClinicalEventType type, string label, string notes = "",
        double? bis = null, double? spo2 = null, double? hr = null, double? sqi = null,
        DateTime? sessionStart = null)
    {
        var ev = new ClinicalEvent
        {
            EventType = type,
            Label = label,
            Notes = notes,
            Timestamp = DateTime.Now,
            BISAtEvent = bis,
            SpO2AtEvent = spo2,
            HRAtEvent = hr,
            SQIAtEvent = sqi,
            IsAutoGenerated = type is ClinicalEventType.AutoAlert_LowBIS
                or ClinicalEventType.AutoAlert_HighBIS
                or ClinicalEventType.AutoAlert_LowSpO2,
            SessionOffset = sessionStart.HasValue ? DateTime.Now - sessionStart.Value : TimeSpan.Zero,
        };
        _events.Add(ev);
        EventAdded?.Invoke(ev);
        _logger.LogInformation("Clinical event recorded: {Event}", ev);
        return ev;
    }

    public void AutoCheckThresholds(double bis, double spo2, double sqi, DateTime sessionStart)
    {
        if (!double.IsNaN(bis))
        {
            if (bis < 40 && !_lowBISAlerted)
            {
                _lowBISAlerted = true;
                AddEvent(ClinicalEventType.AutoAlert_LowBIS, $"BIS < 40 ({bis:F0})",
                    bis: bis, spo2: spo2, sessionStart: sessionStart);
            }
            else if (bis >= 40) _lowBISAlerted = false;

            if (bis > 70 && !_highBISAlerted)
            {
                _highBISAlerted = true;
                AddEvent(ClinicalEventType.AutoAlert_HighBIS, $"BIS > 70 ({bis:F0})",
                    bis: bis, spo2: spo2, sessionStart: sessionStart);
            }
            else if (bis <= 70) _highBISAlerted = false;
        }

        if (!double.IsNaN(spo2) && spo2 < 90 && !_lowSpO2Alerted)
        {
            _lowSpO2Alerted = true;
            AddEvent(ClinicalEventType.AutoAlert_LowSpO2, $"SpO₂ < 90% ({spo2:F0}%)",
                spo2: spo2, sessionStart: sessionStart);
        }
        else if (!double.IsNaN(spo2) && spo2 >= 94) _lowSpO2Alerted = false;
    }
}
