<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>EEGMonitor.AnesthesiaSleep</RootNamespace>
    <AssemblyName>EEGMonitor.AnesthesiaSleep</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EEGMonitor.WPF\EEGMonitor.WPF.csproj" />
  </ItemGroup>

</Project>
